version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: R123456password
            MYSQL_DATABASE: todo_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: devenes123
        networks:
            - devenesnet
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - devenesnet

networks:
    devenesnet:
        driver: bridge